# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 00:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='date published')),
                ('main_body', models.TextField(verbose_name='body')),
                ('subsection1', models.TextField(verbose_name='section 1')),
                ('subsection2', models.TextField(verbose_name='section 2')),
                ('subsection3', models.TextField(verbose_name='section 3')),
            ],
        ),
    ]
