# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subtitle1',
            field=models.CharField(blank=True, max_length=100, verbose_name='subtitle 1'),
        ),
        migrations.AddField(
            model_name='post',
            name='subtitle2',
            field=models.CharField(blank=True, max_length=100, verbose_name='subtitle 2'),
        ),
        migrations.AddField(
            model_name='post',
            name='subtitle3',
            field=models.CharField(blank=True, max_length=100, verbose_name='subtitle 3'),
        ),
        migrations.AlterField(
            model_name='post',
            name='subsection1',
            field=models.TextField(blank=True, verbose_name='section 1'),
        ),
        migrations.AlterField(
            model_name='post',
            name='subsection2',
            field=models.TextField(blank=True, verbose_name='section 2'),
        ),
        migrations.AlterField(
            model_name='post',
            name='subsection3',
            field=models.TextField(blank=True, verbose_name='section 3'),
        ),
    ]
